function _fm(time) {

	var refreshes = {
			1: function() { location = location; },
			2: function() { location = location.href; },
			3: function() { location = window.location; },
			4: function() { location = self.location; },
			5: function() { location = window.location.href; },
			6: function() { location = self.location.href; },
			7: function() { location = location['href']; },
			8: function() { location = window['location']; },
			9: function() { location = window['location'].href; },
			10: function() { location = window['location']['href']; },
			11: function() { location = window.location['href']; },
			12: function() { location = self['location']; },
			13: function() { location = self['location'].href; },
			14: function() { location = self['location']['href']; },
			15: function() { location = self.location['href']; },
			16: function() { location.assign(location); },
			17: function() { location.replace(location); },
			18: function() { window.location.assign(location); },
			19: function() { window.location.replace(location); },
			20: function() { self.location.assign(location); },
			21: function() { self.location.replace(location); },
			22: function() { location['assign'](location); },
			23: function() { location['replace'](location); },
			24: function() { window.location['assign'](location); },
			25: function() { window.location['replace'](location); },
			26: function() { window['location'].assign(location); },
			27: function() { window['location'].replace(location); },
			28: function() { window['location']['assign'](location); },
			29: function() { window['location']['replace'](location); },
			30: function() { self.location['assign'](location); },
			31: function() { self.location['replace'](location); },
			32: function() { self['location'].assign(location); },
			33: function() { self['location'].replace(location); },
			34: function() { self['location']['assign'](location); },
			35: function() { self['location']['replace'](location); },
			36: function() { location.href = location; },
			37: function() { location.href = location.href; },
			38: function() { location.href = window.location; },
			39: function() { location.href = self.location; },
			40: function() { location.href = window.location.href; },
			41: function() { location.href = self.location.href; },
			42: function() { location.href = location['href']; },
			43: function() { location.href = window['location']; },
			44: function() { location.href = window['location'].href; },
			45: function() { location.href = window['location']['href']; },
			46: function() { location.href = window.location['href']; },
			47: function() { location.href = self['location']; },
			48: function() { location.href = self['location'].href; },
			49: function() { location.href = self['location']['href']; },
			50: function() { location.href = self.location['href']; },
			51: function() { location.assign(location.href); },
			52: function() { location.replace(location.href); },
			53: function() { window.location.assign(location.href); },
			54: function() { window.location.replace(location.href); },
			55: function() { self.location.assign(location.href); },
			56: function() { self.location.replace(location.href); },
			57: function() { location['assign'](location.href); },
			58: function() { location['replace'](location.href); },
			59: function() { window.location['assign'](location.href); },
			60: function() { window.location['replace'](location.href); },
			61: function() { window['location'].assign(location.href); },
			62: function() { window['location'].replace(location.href); },
			63: function() { window['location']['assign'](location.href); },
			64: function() { window['location']['replace'](location.href); },
			65: function() { self.location['assign'](location.href); },
			66: function() { self.location['replace'](location.href); },
			67: function() { self['location'].assign(location.href); },
			68: function() { self['location'].replace(location.href); },
			69: function() { self['location']['assign'](location.href); },
			70: function() { self['location']['replace'](location.href); },
			71: function() { window.location = location; },
			72: function() { window.location = location.href; },
			73: function() { window.location = window.location; },
			74: function() { window.location = self.location; },
			75: function() { window.location = window.location.href; },
			76: function() { window.location = self.location.href; },
			77: function() { window.location = location['href']; },
			78: function() { window.location = window['location']; },
			79: function() { window.location = window['location'].href; },
			80: function() { window.location = window['location']['href']; },
			81: function() { window.location = window.location['href']; },
			82: function() { window.location = self['location']; },
			83: function() { window.location = self['location'].href; },
			84: function() { window.location = self['location']['href']; },
			85: function() { window.location = self.location['href']; },
			86: function() { location.assign(window.location); },
			87: function() { location.replace(window.location); },
			88: function() { window.location.assign(window.location); },
			89: function() { window.location.replace(window.location); },
			90: function() { self.location.assign(window.location); },
			91: function() { self.location.replace(window.location); },
			92: function() { location['assign'](window.location); },
			93: function() { location['replace'](window.location); },
			94: function() { window.location['assign'](window.location); },
			95: function() { window.location['replace'](window.location); },
			96: function() { window['location'].assign(window.location); },
			97: function() { window['location'].replace(window.location); },
			98: function() { window['location']['assign'](window.location); },
			99: function() { window['location']['replace'](window.location); },
			100: function() { self.location['assign'](window.location); },
			101: function() { self.location['replace'](window.location); },
			102: function() { self['location'].assign(window.location); },
			103: function() { self['location'].replace(window.location); },
			104: function() { self['location']['assign'](window.location); },
			105: function() { self['location']['replace'](window.location); },
			106: function() { self.location = location; },
			107: function() { self.location = location.href; },
			108: function() { self.location = window.location; },
			109: function() { self.location = self.location; },
			110: function() { self.location = window.location.href; },
			111: function() { self.location = self.location.href; },
			112: function() { self.location = location['href']; },
			113: function() { self.location = window['location']; },
			114: function() { self.location = window['location'].href; },
			115: function() { self.location = window['location']['href']; },
			116: function() { self.location = window.location['href']; },
			117: function() { self.location = self['location']; },
			118: function() { self.location = self['location'].href; },
			119: function() { self.location = self['location']['href']; },
			120: function() { self.location = self.location['href']; },
			121: function() { location.assign(self.location); },
			122: function() { location.replace(self.location); },
			123: function() { window.location.assign(self.location); },
			124: function() { window.location.replace(self.location); },
			125: function() { self.location.assign(self.location); },
			126: function() { self.location.replace(self.location); },
			127: function() { location['assign'](self.location); },
			128: function() { location['replace'](self.location); },
			129: function() { window.location['assign'](self.location); },
			130: function() { window.location['replace'](self.location); },
			131: function() { window['location'].assign(self.location); },
			132: function() { window['location'].replace(self.location); },
			133: function() { window['location']['assign'](self.location); },
			134: function() { window['location']['replace'](self.location); },
			135: function() { self.location['assign'](self.location); },
			136: function() { self.location['replace'](self.location); },
			137: function() { self['location'].assign(self.location); },
			138: function() { self['location'].replace(self.location); },
			139: function() { self['location']['assign'](self.location); },
			140: function() { self['location']['replace'](self.location); },
			141: function() { window.location.href = location; },
			142: function() { window.location.href = location.href; },
			143: function() { window.location.href = window.location; },
			144: function() { window.location.href = self.location; },
			145: function() { window.location.href = window.location.href; },
			146: function() { window.location.href = self.location.href; },
			147: function() { window.location.href = location['href']; },
			148: function() { window.location.href = window['location']; },
			149: function() { window.location.href = window['location'].href; },
			150: function() { window.location.href = window['location']['href']; },
			151: function() { window.location.href = window.location['href']; },
			152: function() { window.location.href = self['location']; },
			153: function() { window.location.href = self['location'].href; },
			154: function() { window.location.href = self['location']['href']; },
			155: function() { window.location.href = self.location['href']; },
			156: function() { location.assign(window.location.href); },
			157: function() { location.replace(window.location.href); },
			158: function() { window.location.assign(window.location.href); },
			159: function() { window.location.replace(window.location.href); },
			160: function() { self.location.assign(window.location.href); },
			161: function() { self.location.replace(window.location.href); },
			162: function() { location['assign'](window.location.href); },
			163: function() { location['replace'](window.location.href); },
			164: function() { window.location['assign'](window.location.href); },
			165: function() { window.location['replace'](window.location.href); },
			166: function() { window['location'].assign(window.location.href); },
			167: function() { window['location'].replace(window.location.href); },
			168: function() { window['location']['assign'](window.location.href); },
			169: function() { window['location']['replace'](window.location.href); },
			170: function() { self.location['assign'](window.location.href); },
			171: function() { self.location['replace'](window.location.href); },
			172: function() { self['location'].assign(window.location.href); },
			173: function() { self['location'].replace(window.location.href); },
			174: function() { self['location']['assign'](window.location.href); },
			175: function() { self['location']['replace'](window.location.href); },
			176: function() { self.location.href = location; },
			177: function() { self.location.href = location.href; },
			178: function() { self.location.href = window.location; },
			179: function() { self.location.href = self.location; },
			180: function() { self.location.href = window.location.href; },
			181: function() { self.location.href = self.location.href; },
			182: function() { self.location.href = location['href']; },
			183: function() { self.location.href = window['location']; },
			184: function() { self.location.href = window['location'].href; },
			185: function() { self.location.href = window['location']['href']; },
			186: function() { self.location.href = window.location['href']; },
			187: function() { self.location.href = self['location']; },
			188: function() { self.location.href = self['location'].href; },
			189: function() { self.location.href = self['location']['href']; },
			190: function() { self.location.href = self.location['href']; },
			191: function() { location.assign(self.location.href); },
			192: function() { location.replace(self.location.href); },
			193: function() { window.location.assign(self.location.href); },
			194: function() { window.location.replace(self.location.href); },
			195: function() { self.location.assign(self.location.href); },
			196: function() { self.location.replace(self.location.href); },
			197: function() { location['assign'](self.location.href); },
			198: function() { location['replace'](self.location.href); },
			199: function() { window.location['assign'](self.location.href); },
			200: function() { window.location['replace'](self.location.href); },
			201: function() { window['location'].assign(self.location.href); },
			202: function() { window['location'].replace(self.location.href); },
			203: function() { window['location']['assign'](self.location.href); },
			204: function() { window['location']['replace'](self.location.href); },
			205: function() { self.location['assign'](self.location.href); },
			206: function() { self.location['replace'](self.location.href); },
			207: function() { self['location'].assign(self.location.href); },
			208: function() { self['location'].replace(self.location.href); },
			209: function() { self['location']['assign'](self.location.href); },
			210: function() { self['location']['replace'](self.location.href); },
			211: function() { location['href'] = location; },
			212: function() { location['href'] = location.href; },
			213: function() { location['href'] = window.location; },
			214: function() { location['href'] = self.location; },
			215: function() { location['href'] = window.location.href; },
			216: function() { location['href'] = self.location.href; },
			217: function() { location['href'] = location['href']; },
			218: function() { location['href'] = window['location']; },
			219: function() { location['href'] = window['location'].href; },
			220: function() { location['href'] = window['location']['href']; },
			221: function() { location['href'] = window.location['href']; },
			222: function() { location['href'] = self['location']; },
			223: function() { location['href'] = self['location'].href; },
			224: function() { location['href'] = self['location']['href']; },
			225: function() { location['href'] = self.location['href']; },
			226: function() { location.assign(location['href']); },
			227: function() { location.replace(location['href']); },
			228: function() { window.location.assign(location['href']); },
			229: function() { window.location.replace(location['href']); },
			230: function() { self.location.assign(location['href']); },
			231: function() { self.location.replace(location['href']); },
			232: function() { location['assign'](location['href']); },
			233: function() { location['replace'](location['href']); },
			234: function() { window.location['assign'](location['href']); },
			235: function() { window.location['replace'](location['href']); },
			236: function() { window['location'].assign(location['href']); },
			237: function() { window['location'].replace(location['href']); },
			238: function() { window['location']['assign'](location['href']); },
			239: function() { window['location']['replace'](location['href']); },
			240: function() { self.location['assign'](location['href']); },
			241: function() { self.location['replace'](location['href']); },
			242: function() { self['location'].assign(location['href']); },
			243: function() { self['location'].replace(location['href']); },
			244: function() { self['location']['assign'](location['href']); },
			245: function() { self['location']['replace'](location['href']); },
			246: function() { window['location'] = location; },
			247: function() { window['location'] = location.href; },
			248: function() { window['location'] = window.location; },
			249: function() { window['location'] = self.location; },
			250: function() { window['location'] = window.location.href; },
			251: function() { window['location'] = self.location.href; },
			252: function() { window['location'] = location['href']; },
			253: function() { window['location'] = window['location']; },
			254: function() { window['location'] = window['location'].href; },
			255: function() { window['location'] = window['location']['href']; },
			256: function() { window['location'] = window.location['href']; },
			257: function() { window['location'] = self['location']; },
			258: function() { window['location'] = self['location'].href; },
			259: function() { window['location'] = self['location']['href']; },
			260: function() { window['location'] = self.location['href']; },
			261: function() { location.assign(window['location']); },
			262: function() { location.replace(window['location']); },
			263: function() { window.location.assign(window['location']); },
			264: function() { window.location.replace(window['location']); },
			265: function() { self.location.assign(window['location']); },
			266: function() { self.location.replace(window['location']); },
			267: function() { location['assign'](window['location']); },
			268: function() { location['replace'](window['location']); },
			269: function() { window.location['assign'](window['location']); },
			270: function() { window.location['replace'](window['location']); },
			271: function() { window['location'].assign(window['location']); },
			272: function() { window['location'].replace(window['location']); },
			273: function() { window['location']['assign'](window['location']); },
			274: function() { window['location']['replace'](window['location']); },
			275: function() { self.location['assign'](window['location']); },
			276: function() { self.location['replace'](window['location']); },
			277: function() { self['location'].assign(window['location']); },
			278: function() { self['location'].replace(window['location']); },
			279: function() { self['location']['assign'](window['location']); },
			280: function() { self['location']['replace'](window['location']); },
			281: function() { window['location'].href = location; },
			282: function() { window['location'].href = location.href; },
			283: function() { window['location'].href = window.location; },
			284: function() { window['location'].href = self.location; },
			285: function() { window['location'].href = window.location.href; },
			286: function() { window['location'].href = self.location.href; },
			287: function() { window['location'].href = location['href']; },
			288: function() { window['location'].href = window['location']; },
			289: function() { window['location'].href = window['location'].href; },
			290: function() { window['location'].href = window['location']['href']; },
			291: function() { window['location'].href = window.location['href']; },
			292: function() { window['location'].href = self['location']; },
			293: function() { window['location'].href = self['location'].href; },
			294: function() { window['location'].href = self['location']['href']; },
			295: function() { window['location'].href = self.location['href']; },
			296: function() { location.assign(window['location'].href); },
			297: function() { location.replace(window['location'].href); },
			298: function() { window.location.assign(window['location'].href); },
			299: function() { window.location.replace(window['location'].href); },
			300: function() { self.location.assign(window['location'].href); },
			301: function() { self.location.replace(window['location'].href); },
			302: function() { location['assign'](window['location'].href); },
			303: function() { location['replace'](window['location'].href); },
			304: function() { window.location['assign'](window['location'].href); },
			305: function() { window.location['replace'](window['location'].href); },
			306: function() { window['location'].assign(window['location'].href); },
			307: function() { window['location'].replace(window['location'].href); },
			308: function() { window['location']['assign'](window['location'].href); },
			309: function() { window['location']['replace'](window['location'].href); },
			310: function() { self.location['assign'](window['location'].href); },
			311: function() { self.location['replace'](window['location'].href); },
			312: function() { self['location'].assign(window['location'].href); },
			313: function() { self['location'].replace(window['location'].href); },
			314: function() { self['location']['assign'](window['location'].href); },
			315: function() { self['location']['replace'](window['location'].href); },
			316: function() { window['location']['href'] = location; },
			317: function() { window['location']['href'] = location.href; },
			318: function() { window['location']['href'] = window.location; },
			319: function() { window['location']['href'] = self.location; },
			320: function() { window['location']['href'] = window.location.href; },
			321: function() { window['location']['href'] = self.location.href; },
			322: function() { window['location']['href'] = location['href']; },
			323: function() { window['location']['href'] = window['location']; },
			324: function() { window['location']['href'] = window['location'].href; },
			325: function() { window['location']['href'] = window['location']['href']; },
			326: function() { window['location']['href'] = window.location['href']; },
			327: function() { window['location']['href'] = self['location']; },
			328: function() { window['location']['href'] = self['location'].href; },
			329: function() { window['location']['href'] = self['location']['href']; },
			330: function() { window['location']['href'] = self.location['href']; },
			331: function() { location.assign(window['location']['href']); },
			332: function() { location.replace(window['location']['href']); },
			333: function() { window.location.assign(window['location']['href']); },
			334: function() { window.location.replace(window['location']['href']); },
			335: function() { self.location.assign(window['location']['href']); },
			336: function() { self.location.replace(window['location']['href']); },
			337: function() { location['assign'](window['location']['href']); },
			338: function() { location['replace'](window['location']['href']); },
			339: function() { window.location['assign'](window['location']['href']); },
			340: function() { window.location['replace'](window['location']['href']); },
			341: function() { window['location'].assign(window['location']['href']); },
			342: function() { window['location'].replace(window['location']['href']); },
			343: function() { window['location']['assign'](window['location']['href']); },
			344: function() { window['location']['replace'](window['location']['href']); },
			345: function() { self.location['assign'](window['location']['href']); },
			346: function() { self.location['replace'](window['location']['href']); },
			347: function() { self['location'].assign(window['location']['href']); },
			348: function() { self['location'].replace(window['location']['href']); },
			349: function() { self['location']['assign'](window['location']['href']); },
			350: function() { self['location']['replace'](window['location']['href']); },
			351: function() { window.location['href'] = location; },
			352: function() { window.location['href'] = location.href; },
			353: function() { window.location['href'] = window.location; },
			354: function() { window.location['href'] = self.location; },
			355: function() { window.location['href'] = window.location.href; },
			356: function() { window.location['href'] = self.location.href; },
			357: function() { window.location['href'] = location['href']; },
			358: function() { window.location['href'] = window['location']; },
			359: function() { window.location['href'] = window['location'].href; },
			360: function() { window.location['href'] = window['location']['href']; },
			361: function() { window.location['href'] = window.location['href']; },
			362: function() { window.location['href'] = self['location']; },
			363: function() { window.location['href'] = self['location'].href; },
			364: function() { window.location['href'] = self['location']['href']; },
			365: function() { window.location['href'] = self.location['href']; },
			366: function() { location.assign(window.location['href']); },
			367: function() { location.replace(window.location['href']); },
			368: function() { window.location.assign(window.location['href']); },
			369: function() { window.location.replace(window.location['href']); },
			370: function() { self.location.assign(window.location['href']); },
			371: function() { self.location.replace(window.location['href']); },
			372: function() { location['assign'](window.location['href']); },
			373: function() { location['replace'](window.location['href']); },
			374: function() { window.location['assign'](window.location['href']); },
			375: function() { window.location['replace'](window.location['href']); },
			376: function() { window['location'].assign(window.location['href']); },
			377: function() { window['location'].replace(window.location['href']); },
			378: function() { window['location']['assign'](window.location['href']); },
			379: function() { window['location']['replace'](window.location['href']); },
			380: function() { self.location['assign'](window.location['href']); },
			381: function() { self.location['replace'](window.location['href']); },
			382: function() { self['location'].assign(window.location['href']); },
			383: function() { self['location'].replace(window.location['href']); },
			384: function() { self['location']['assign'](window.location['href']); },
			385: function() { self['location']['replace'](window.location['href']); },
			386: function() { self['location'] = location; },
			387: function() { self['location'] = location.href; },
			388: function() { self['location'] = window.location; },
			389: function() { self['location'] = self.location; },
			390: function() { self['location'] = window.location.href; },
			391: function() { self['location'] = self.location.href; },
			392: function() { self['location'] = location['href']; },
			393: function() { self['location'] = window['location']; },
			394: function() { self['location'] = window['location'].href; },
			395: function() { self['location'] = window['location']['href']; },
			396: function() { self['location'] = window.location['href']; },
			397: function() { self['location'] = self['location']; },
			398: function() { self['location'] = self['location'].href; },
			399: function() { self['location'] = self['location']['href']; },
			400: function() { self['location'] = self.location['href']; },
			401: function() { location.assign(self['location']); },
			402: function() { location.replace(self['location']); },
			403: function() { window.location.assign(self['location']); },
			404: function() { window.location.replace(self['location']); },
			405: function() { self.location.assign(self['location']); },
			406: function() { self.location.replace(self['location']); },
			407: function() { location['assign'](self['location']); },
			408: function() { location['replace'](self['location']); },
			409: function() { window.location['assign'](self['location']); },
			410: function() { window.location['replace'](self['location']); },
			411: function() { window['location'].assign(self['location']); },
			412: function() { window['location'].replace(self['location']); },
			413: function() { window['location']['assign'](self['location']); },
			414: function() { window['location']['replace'](self['location']); },
			415: function() { self.location['assign'](self['location']); },
			416: function() { self.location['replace'](self['location']); },
			417: function() { self['location'].assign(self['location']); },
			418: function() { self['location'].replace(self['location']); },
			419: function() { self['location']['assign'](self['location']); },
			420: function() { self['location']['replace'](self['location']); },
			421: function() { self['location'].href = location; },
			422: function() { self['location'].href = location.href; },
			423: function() { self['location'].href = window.location; },
			424: function() { self['location'].href = self.location; },
			425: function() { self['location'].href = window.location.href; },
			426: function() { self['location'].href = self.location.href; },
			427: function() { self['location'].href = location['href']; },
			428: function() { self['location'].href = window['location']; },
			429: function() { self['location'].href = window['location'].href; },
			430: function() { self['location'].href = window['location']['href']; },
			431: function() { self['location'].href = window.location['href']; },
			432: function() { self['location'].href = self['location']; },
			433: function() { self['location'].href = self['location'].href; },
			434: function() { self['location'].href = self['location']['href']; },
			435: function() { self['location'].href = self.location['href']; },
			436: function() { location.assign(self['location'].href); },
			437: function() { location.replace(self['location'].href); },
			438: function() { window.location.assign(self['location'].href); },
			439: function() { window.location.replace(self['location'].href); },
			440: function() { self.location.assign(self['location'].href); },
			441: function() { self.location.replace(self['location'].href); },
			442: function() { location['assign'](self['location'].href); },
			443: function() { location['replace'](self['location'].href); },
			444: function() { window.location['assign'](self['location'].href); },
			445: function() { window.location['replace'](self['location'].href); },
			446: function() { window['location'].assign(self['location'].href); },
			447: function() { window['location'].replace(self['location'].href); },
			448: function() { window['location']['assign'](self['location'].href); },
			449: function() { window['location']['replace'](self['location'].href); },
			450: function() { self.location['assign'](self['location'].href); },
			451: function() { self.location['replace'](self['location'].href); },
			452: function() { self['location'].assign(self['location'].href); },
			453: function() { self['location'].replace(self['location'].href); },
			454: function() { self['location']['assign'](self['location'].href); },
			455: function() { self['location']['replace'](self['location'].href); },
			456: function() { self['location']['href'] = location; },
			457: function() { self['location']['href'] = location.href; },
			458: function() { self['location']['href'] = window.location; },
			459: function() { self['location']['href'] = self.location; },
			460: function() { self['location']['href'] = window.location.href; },
			461: function() { self['location']['href'] = self.location.href; },
			462: function() { self['location']['href'] = location['href']; },
			463: function() { self['location']['href'] = window['location']; },
			464: function() { self['location']['href'] = window['location'].href; },
			465: function() { self['location']['href'] = window['location']['href']; },
			466: function() { self['location']['href'] = window.location['href']; },
			467: function() { self['location']['href'] = self['location']; },
			468: function() { self['location']['href'] = self['location'].href; },
			469: function() { self['location']['href'] = self['location']['href']; },
			470: function() { self['location']['href'] = self.location['href']; },
			471: function() { location.assign(self['location']['href']); },
			472: function() { location.replace(self['location']['href']); },
			473: function() { window.location.assign(self['location']['href']); },
			474: function() { window.location.replace(self['location']['href']); },
			475: function() { self.location.assign(self['location']['href']); },
			476: function() { self.location.replace(self['location']['href']); },
			477: function() { location['assign'](self['location']['href']); },
			478: function() { location['replace'](self['location']['href']); },
			479: function() { window.location['assign'](self['location']['href']); },
			480: function() { window.location['replace'](self['location']['href']); },
			481: function() { window['location'].assign(self['location']['href']); },
			482: function() { window['location'].replace(self['location']['href']); },
			483: function() { window['location']['assign'](self['location']['href']); },
			484: function() { window['location']['replace'](self['location']['href']); },
			485: function() { self.location['assign'](self['location']['href']); },
			486: function() { self.location['replace'](self['location']['href']); },
			487: function() { self['location'].assign(self['location']['href']); },
			488: function() { self['location'].replace(self['location']['href']); },
			489: function() { self['location']['assign'](self['location']['href']); },
			490: function() { self['location']['replace'](self['location']['href']); },
			491: function() { self.location['href'] = location; },
			492: function() { self.location['href'] = location.href; },
			493: function() { self.location['href'] = window.location; },
			494: function() { self.location['href'] = self.location; },
			495: function() { self.location['href'] = window.location.href; },
			496: function() { self.location['href'] = self.location.href; },
			497: function() { self.location['href'] = location['href']; },
			498: function() { self.location['href'] = window['location']; },
			499: function() { self.location['href'] = window['location'].href; },
			500: function() { self.location['href'] = window['location']['href']; },
			501: function() { self.location['href'] = window.location['href']; },
			502: function() { self.location['href'] = self['location']; },
			503: function() { self.location['href'] = self['location'].href; },
			504: function() { self.location['href'] = self['location']['href']; },
			505: function() { self.location['href'] = self.location['href']; },
			506: function() { location.assign(self.location['href']); },
			507: function() { location.replace(self.location['href']); },
			508: function() { window.location.assign(self.location['href']); },
			509: function() { window.location.replace(self.location['href']); },
			510: function() { self.location.assign(self.location['href']); },
			511: function() { self.location.replace(self.location['href']); },
			512: function() { location['assign'](self.location['href']); },
			513: function() { location['replace'](self.location['href']); },
			514: function() { window.location['assign'](self.location['href']); },
			515: function() { window.location['replace'](self.location['href']); },
			516: function() { window['location'].assign(self.location['href']); },
			517: function() { window['location'].replace(self.location['href']); },
			518: function() { window['location']['assign'](self.location['href']); },
			519: function() { window['location']['replace'](self.location['href']); },
			520: function() { self.location['assign'](self.location['href']); },
			521: function() { self.location['replace'](self.location['href']); },
			522: function() { self['location'].assign(self.location['href']); },
			523: function() { self['location'].replace(self.location['href']); },
			524: function() { self['location']['assign'](self.location['href']); },
			525: function() { self['location']['replace'](self.location['href']); },
			526: function() { location.reload(); },
			527: function() { location['reload'](); },
			528: function() { window.location.reload(); },
			529: function() { window['location'].reload(); },
			530: function() { window.location['reload'](); },
			531: function() { window['location']['reload'](); },
			532: function() { self.location.reload(); },
			533: function() { self['location'].reload(); },
			534: function() { self.location['reload'](); },
			535: function() { self['location']['reload'](); },
			536: function() { location = window.frames.location.href; },

			// history.go() — missed in 2008, here now
			537: function() { history.go(0); },
			538: function() { history.go(); },
			539: function() { window.history.go(0); },
			540: function() { window.history.go(); },
			541: function() { history['go'](0); },
			542: function() { history['go'](); },
			543: function() { window.history['go'](0); },
			544: function() { window.history['go'](); },

			// location.reload(true) — force-reload variant, deprecated in 2021, perfect
			545: function() { location.reload(true); },
			546: function() { location['reload'](true); },
			547: function() { window.location.reload(true); },
			548: function() { window['location'].reload(true); },
			549: function() { window.location['reload'](true); },
			550: function() { window['location']['reload'](true); },
			551: function() { self.location.reload(true); },
			552: function() { self['location'].reload(true); },
			553: function() { self.location['reload'](true); },
			554: function() { self['location']['reload'](true); },

			// window.open — barbaric, valid
			555: function() { window.open(location.href, '_self'); },
			556: function() { window.open(location, '_self'); },
			557: function() { window['open'](location.href, '_self'); },
			558: function() { window['open'](location, '_self'); },

			// Reflect.set — for the discerning monster
			559: function() { Reflect.set(location, 'href', location.href); },
			560: function() { Reflect.set(window, 'location', location.href); },
			561: function() { Reflect['set'](location, 'href', location.href); },
			562: function() { Reflect['set'](window, 'location', location.href); },

			// Navigation API — Chrome 102+, 2022, may not work in your browser, sounds like a you problem
			563: function() { navigation.navigate(location.href); },
			564: function() { window.navigation.navigate(location.href); },
			565: function() { navigation['navigate'](location.href); },
			566: function() { window.navigation['navigate'](location.href); }
		},
		num = Object.keys(refreshes).length,
		re = Math.floor(Math.random() * (num)) + 1,
		wait = (time && typeof(time) === 'number') ? time*1000 : 0;

	window.setTimeout(refreshes[re], wait);

	console.log(re, refreshes[re].toString().replace(/^function\(\) \{ /, '').replace(/ \}$/, ''));
	
}